### ISSUE TITLE
filter out common words from plot and actor

### ISSUE THREAD

**Issue by WesleyYep** [WesleyYep/moviebot#41]
eg "a dog" -> "dog"

**Comment by Wal8800** [comment]
"the", "to"

**Comment by Wal8800** [comment]
Current stopword list: 
[ "and", "is", "the", "a", "are", "was", "an", "to", "such", "as", "there", "then", "these"']

**Comment by Wal8800** [comment]
movies-v8 index deinfition:
https://github.com/WesleyYep/moviebot/wiki/Movie-Index-definition
